# Generated by Django 4.2.7 on 2023-12-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='id',
        ),
        migrations.AlterField(
            model_name='corrproffgrop',
            name='id_group',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='corrproffgrop',
            name='id_professor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='attendance',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='id_student',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='progress',
            name='mark',
            field=models.IntegerField(),
        ),
    ]
