# Generated by Django 4.2.7 on 2023-12-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_group_subjects_remove_subject_professors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subjects',
            field=models.ManyToManyField(to='main.subject'),
        ),
    ]
