# Generated by Django 4.2.7 on 2023-12-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_group_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='subjects',
            field=models.ManyToManyField(related_name='groups', to='main.subject'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(related_name='professors', to='main.subject'),
        ),
    ]
