# Generated by Django 4.2.7 on 2023-12-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_group_subjects_alter_user_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='attendance',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='progress',
            name='comment',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='progress',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='progress',
            name='mark',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
