# Generated by Django 4.2.7 on 2023-12-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_progress_attendance_progress_comment_progress_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
    ]
