# Generated by Django 4.2.7 on 2023-12-16 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_progress_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkCell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='progress',
            name='date',
        ),
        migrations.AddField(
            model_name='progress',
            name='markcell',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.markcell'),
            preserve_default=False,
        ),
    ]
