# Generated by Django 4.2.7 on 2023-12-16 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_markcell_remove_progress_date_progress_markcell'),
    ]

    operations = [
        migrations.AddField(
            model_name='markcell',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.subject'),
            preserve_default=False,
        ),
    ]
